name: Build zie-toolbox image
on:
  schedule:
    - cron: '0 1 * * 1'  #  1am every monday
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  cli-tools-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ github.token }}
        - uses: actions/checkout@v4
          with:
            ref: tbx-cli-tools
        - name: Toolbox CLI Tools Build
          run: make

# origin HEAD:main

