name: Build
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build wolfi image
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - name: Neovim latest release sha
        shell: bash
        run: |
          NEW=$(curl https://api.github.com/repos/neovim/neovim/releases -s | jq -r '.[0].target_commitish') 
          OLD=$(grep -oP 'sha: \K.+$' neovim.yaml ) || true
          echo "old: ${OLD}"   
          echo "new: ${NEW}"
          sed -i "s/$${OLD}/$${NEW}/" neovim.yaml
      - uses: sigstore/cosign-installer@main
      - uses: chainguard-dev/actions/melange-build@main
        with:
          sign-with-temporary-key: true
          empty-workspace: true
          config: neovim.yaml
      - uses: chainguard-dev/actions/apko-build@main
        id: apko
        with:
          archs: x86_64
          keyring-append: /github/workspace/melange.rsa.pub
          tag: ghcr.io/${{ github.repository }}:latest
          source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
      - uses: docker/login-action@v3
        with:
          registry: cgr.dev
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - shell: bash
        run: |
          # TODO: Add attributes based on things like the commit.
          COSIGN_EXPERIMENTAL=true cosign sign ${{ steps.apko.outputs.digest }}
          ls -al .
          podman images
    
