name: Build
on:
  schedule:
    - cron: '0 1 * * 1'  #  1am every monday
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build
        shell: bash
        run: make bldr-luarocks
#     - uses: sigstore/cosign-installer@main
#     - uses: chainguard-dev/actions/melange-build@main
#       with:
#         sign-with-temporary-key: true
#         empty-workspace: true
#         config: neovim.yaml
