name: Build zie-toolbox image
on:
  schedule:
    - cron: '0 1 * * 1'  #  1am every monday
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/checkout@v4
      # - name: Toolbox Build
      #   run: make
      - name: Commit changes
        run: |
          cat info/toolbox_intro.md | tee README.md
          cat info/toolbox_overview.md | tee -a README.md
          cat info/toolbox_getting_started.md | tee -a README.md
          git config user.name ${{ github.repository_owner }}
          git config user.email "grantmacken@gmail.com"
          git commit README.md -m "Update README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
