name: Build
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build wolfi image
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Neovim latest release sha
        shell: bash
        run: |
          NEW=$(curl https://api.github.com/repos/neovim/neovim/releases -s | jq -r '.[0].target_commitish') 
          OLD=$(grep -oP 'sha: \K.+$' neovim.yaml ) || true
          echo "old: ${OLD}"   
          echo "new: ${NEW}"
          sed -i "s/$${OLD}/$${NEW}/" neovim.yaml
      - uses: sigstore/cosign-installer@main
      - uses: chainguard-dev/actions/melange-build@main
        with:
          sign-with-temporary-key: true
          empty-workspace: true
          config: neovim.yaml
      - name: Check melange build
        shell: bash
        run: ls -al .
      - name: Apko build
        shell: bash
        run: |
          podman run --rm --privileged -v "$${PWD}":/work -w /work \
          cgr.dev/chainguard/melange build neovim.yaml \
          --arch x86_64 \
          --signing-key melange.rsa \
          --keyring-append melange.rsa.pub
      - name: Check apko build
        shell: bash
        run: ls -al .

    
