name: Build
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build wolfi image
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@main
   
  
    
