name: Build
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build wolfi image
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Check melange build
        shell: bash
        run: make bldr-neovim
      - name: Apko build
        shell: bash
        run: |
          podman run --rm --privileged -v "${PWD}":/work -w /work cgr.dev/chainguard/apko build apko.yaml apko-wolfi:latest apko-wolfi.tar
      - name: Wolfi os distrobox build
        shell: bash
        run: make
#     - uses: sigstore/cosign-installer@main
#     - uses: chainguard-dev/actions/melange-build@main
#       with:
#         sign-with-temporary-key: true
#         empty-workspace: true
#         config: neovim.yaml
#     - name: Check melange build
#       shell: bash
#       run: |
#         pwd
#         ls -al .
#         ls -alR packages || true
#         cat packages/x86_64/APKINDEX.json | jq '.'
#   
