name: Build zie-toolbox image
on:
  schedule:
    - cron: '0 1 * * 2'  #  1am every monday
  push:
    branches:
    - tbx-cli-tools
    paths-ignore:
    - '**/README.md'
jobs:
  build:
    name: Build tbx-cli-tools Image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/checkout@v4
      - name: Toolbox Build
        run: |
          printf "%s\n" " - building tbx-cli-tools Image"
          printenv
          ls -al /usr/bin | grep bash || true
          echo '+++++++++++++++'
          make
