name: CI
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  bldr_go:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build go cli tools
      run: make bldr-go
    - name: UploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: bldr-go
        path: bldr-go.tar
        retention-days: 1
  bldr_rust:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build rust cli tools
      run: make bldr-rust
    - name: UploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: bldr-rust
        path: bldr-rust.tar
        retention-days: 1
  zie-toolbox:
    runs-on: ubuntu-latest
    needs: [bldr_go, bldr_rust]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
    - name: check
      run: |
        ls -al bldr-go
        ls -al bldr-rust
        podman load --quiet --input bldr-go/bldr-go.tar | podman load
        podman load --quiet --input bldr-rust/bldr-rust.tar | podman load
        podman images

#       podman load --quiet -i fedora.tar.gz
# jobs:
#   bldr_go:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Build 
#       run: make bldr-go
# jobs:
#   zie_wolfi-toolbox:
#     runs-on: ubuntu-latest
#     needs: [bldr-rust, bldr-go]
#     permissions:
#       contents: read
#       packages: write
#       id-token: write
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Log in to ghcr.io
#       uses: docker/login-action@v3
#       with:
#         username: ${{ github.repository_owner }}
#         password: ${{ github.token }}
#         registry: ghcr.io
#     - name: Build 
#       run: podman images
