name: CI
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  bldr_go:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build go cli tools
      run: make bldr-go
    - name: UploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: bldr-go
        path: bldr-go.tar
        retention-days: 1
  bldr_rust:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build rust cli tools
      run: make bldr-rust
    - name: UploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: bldr-rust
        path: bldr-rust.tar
        retention-days: 1
  zie-toolbox:
    runs-on: ubuntu-latest
    needs: [bldr_go, bldr_rust]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      uses: docker/login-action@v3
    - name: Login
      with:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        registry: ghcr.io
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v4
    - name: Load
      run: |
        podman load --quiet --input bldr-go/bldr-go.tar
        podman load --quiet --input bldr-rust/bldr-rust.tar
        podman images
    - name: Build 
      run: make zie-toolbox
    - name: Check 
      run: podman images
