name: CI
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
env:
  REGISTRY: 'ghcr.io/${{ github.repository_owner }}'
  NAME: 'tbx-wolfi-core'
jobs:
  zie_wolfi-toolbox:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        registry: ${{ env.REGISTRY }}
    - name: Build
      run: |
        set -euxo pipefail
        CONTAINER=$(buildah from cgr.dev/chainguard/wolfi-base)
        buildah config \
          --label com.github.containers.toolbox='true' \
          --label usage='This image is meant to be used with the toolbox command' \
          --label summary='a Wolfi based toolbox' \
          --label maintainer='Grant MacKenzie <grantmacken@gmail.com>' ${CONTAINER}
        buildah run ${CONTAINER} sh -c 'apk update && apk upgrade'
        # buildah run ${CONTAINER} sh -c 'apk info -vv | sort'
        buildah run ${CONTAINER} sh -c 'apk add bash git grep command-not-found procps sudo-rs'
        buildah run ${CONTAINER} /bin/bash -c 'apk add curl findmnt gpg mount pigz rsync umount xauth zip' 
	      buildah run $${CONTAINER} /bin/bash -c 'apk add coreutils diffutils findutils gnupg iproute2 iputils keyutils libcap mount ncurses ncurses-terminfo net-tools openssh-client posix-libc-utils su-exec tcpdump tzdata util-linux util-linux-misc xz vulkan-loader'
	      # Add Distrobox-host-exec
	      buildah add $${CONTAINER} 'https://raw.githubusercontent.com/89luca89/distrobox/main/distrobox-host-exec' '/usr/bin/distrobox-host-exec'
	      HOST_SPAWN_VERSION=$$(buildah run $${CONTAINER} /bin/bash -c 'grep -oP "host_spawn_version=\K.+" /usr/bin/distrobox-host-exec')
	      echo $$HOST_SPAWN_VERSION
	      # Give UID = 1000 sudo
        buildah run ${CONTAINER} sh -c 'echo "#1000 ALL = (root) NOPASSWD:ALL" >> /etc/sudoers'
        # sh as bash
        buildah run ${CONTAINER} sh -c 'sed -i -e "/^root/s/\/bin\/ash/\/bin\/bash/" /etc/passwd'
        buildah commit --rm $${CONTAINER} tbx-base


        # buildah run ${CONTAINER} sh -c 'cd neovim && make \
        #   CMAKE_BUILD_TYPE=RelWithDebInfo \
        #   CMAKE_INSTALL_PREFIX=/usr \
        #   CMAKE_INSTALL_LIBDIR=lib \
        #   && make install'
        # buildah run ${CONTAINER} sh -c 'which nvim && nvim --version'
        # buildah run ${CONTAINER} sh -c 'cd ../ && rm -R neovim'
        # buildah copy ${CONTAINER} 'https://raw.githubusercontent.com/ublue-os/bluefin/main/toolboxes/files.bluefin-cli/etc/pam.d/sudo' '/etc/pam.d/sudo'  
        # buildah copy ${CONTAINER} 'https://raw.githubusercontent.com/ublue-os/bluefin/main/toolboxes/files.bluefin-cli/etc/pam.d/sudo-i' '/etc/pam.d/sudo-i'  
        # buildah copy ${CONTAINER} 'https://raw.githubusercontent.com/ublue-os/bluefin/main/toolboxes/files.bluefin-cli/etc/sudoers' '/etc/sudoers'  
        # # buildah run ${CONTAINER} sh -c 'chown -R 1000 /home/linuxbrew'
        # buildah run ${CONTAINER} sh -c 'sed -i -e "/^root/s/\/bin\/ash/\/bin\/bash/" /etc/passwd'
        # buildah run ${CONTAINER} sh -c 'cat /etc/passwd'
        # buildah commit ${CONTAINER} ${REGISTRY}/${NAME}:latest
        # buildah push ${REGISTRY}/${NAME}:latest

    #     # wolfi toolbox core files @see https://github.com/ublue-os/bluefin/blob/main/toolboxes/packages.wolfi
    #     # buildah run ${CONTAINER} sh -c 'apk add \
    #     #   bash bzip2 coreutils curl diffutils findmnt findutils gnupg gpg iproute2 iputils keyutils libcap mount \
    #     #   ncurses ncurses-terminfo net-tools openssh-client pigz posix-libc-utils procps rsync su-exec tcpdump tree \
    #     #   tzdata umount util-linux util-linux-misc wget xz zip vulkan-loader'
    #       # buildah run ${CONTAINER} sh -c 'apk add git'
    #     # Change root shell to BASH
    #     # Have Linuxbrew owned by UID = 1000
    #     buildah run ${CONTAINER} sh -c 'chown -R 1000 /home/linuxbrew'
    #     buildah run ${CONTAINER} sh -c 'sed -i -e "/^root/s/\/bin\/ash/\/bin\/bash/" /etc/passwd'
    #     buildah run ${CONTAINER} sh -c 'cat /etc/passwd'

    #     # podman start --attach 
    #
    #     # https://github.com/ublue-os/bluefin/issues/576
