name: CI
on: 
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
env:
  REGISTRY: 
  NAME: 'zie-toolbox'
jobs:
  bldr_rust:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build 
      run: make bldr-rust
jobs:
  bldr_go:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build 
      run: make bldr-go
jobs:
  zie_wolfi-toolbox:
    runs-on: ubuntu-latest
    needs: [bldr-rust, bldr-go]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Log in to ghcr.io
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        registry: ghcr.io
    - name: Build 
      run: echo 'hi'
