name: CI
on:
  push:
    branches:
    - main
    paths-ignore:
    - '**/README.md'
jobs:
  bldr_distrobox:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
        registry: ghcr.io
    - name: Build with apko
      run: cd wolfi && make
    - name: Create zie-wolfi-toolbox
      run: make zie-wolfi-toolbox


